### PR TITLE
Automated testing setup

### PR DESCRIPTION
**Pull request by christianvluu**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [x] Optimization
- [x] Documentation Update

## Description
* Added an additional docker container for automated testing
* Added additional automated testing docker container launch flag to ./setup_XXX.sh
* Updated documentation
* Split docker-compose files into difference launch cases (gpu + automated testing)
* Set appropriate hostnames for docker containers
* Connects the automated testing docker container with the autonomy docker container for ROS

## QA Instructions, Screenshots, Recordings
* Run `./setup.dev --run-testing`
* Go into autonomy docker (`robobuggy2-main-1`)
* In another terminal window, go into tester docker (`robobuggy2-tester-1`)
* Roslaunch the sim in the autonomy docker
* *In the tester docker* --> Rostopic list or echo some topic from the autonomy docker
* You should see topics being echoed over

Running `./setup_dev.sh` without the `--run-testing` flag will *NOT* launch the automated testing docker container.

image

### CODE REVIEW

**Comment by Jackack** [comment]
Tested, works on Macbook Air.

**Comment by Jackack** [comment]
What's TEMP_DO_NOT_EDIT.txt

**Comment by christianvluu** [comment]
Temp requirements file bc docker requires them to be in the same directors per container. Figured it was kinda này to have the same file in two places so the setup scripts will copy them as needed from the root directory. Hence they are ignored by git and overwritten each time the container is spooled up.

> What's TEMP_DO_NOT_EDIT.txt

**Comment by christianvluu** [comment]
^^ see line 82 onwards in setup dev for instance.

**Review by Jackack — APPROVED** [review]

**Comment by maya-doshi** [comment]
It works for me on Fedora 39.

I had to make some fedora specific changes (These aren't important for the current merge though)
- Replace all `docker compose` with `docker-compose`
- `sudo chcon -Rt svirt_sandbox_file_t ./r
b_ws` to allow folder access with SELinux active. (There was a way to fix this through the docker compose file iirc)

**Review by maya-doshi — APPROVED** [review]

**Pull request merged**
