### PR TITLE
Jackack/nand sim

### PR DESCRIPTION
**Pull request by Jackack**
launch files for the updated sim

### CODE REVIEW

**Comment by christianvluu** [comment]
Screenshot 2023-11-17 at 1 41 55 PM

^^ Conversation with jack

**Review by christianvluu — APPROVED** [review]
See screenshot for proof

**Comment by Jackack** [comment]
toxic


> See screenshot for proof

**Comment by christianvluu** [comment]
Screenshot 2023-11-17 at 1 43 29 PM

**Comment by Jackack** [comment]
> Screenshot 2023-11-17 at 1 43 29 PM

smh

**Pull request merged**
