### PR TITLE
Sim launch position arg

### PR DESCRIPTION
**Pull request by PatXue**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Changed arguments in single and 2 buggy simulator launch files to allow user to start buggy(s) from any distance along the planned trajectory by passing in command line arguments.

## QA Instructions, Screenshots, Recordings
Tested single buggy sim on both Gabe's and my computer, and appears to behave as expected. Tested double buggy sim on my computer, and also seems to work as expected.

### CODE REVIEW

**Comment by christianvluu** [comment]
I was imagining we have certain "keypoints/checkpoints" around the course where the buggies could start, instead of inputting a distance.

Perhaps there's a different option upon launching that could allow you to specify the start location down to the particular coordinate/distance along the path, but in general, we're only going to be starting the simulation at a few positions right? @Jackack

**Comment by Jackack** [comment]
The idea is to use distance to specify the key points

**Review by Jackack — CHANGES_REQUESTED** [review]
In engine.py, can you add the ability to pass starting position as a utm cooridnate as well?

**Comment by christianvluu** [comment]
Yeah, was gonna ask what if we want to start slightly off from the path.

**Review by christianvluu — CHANGES_REQUESTED** [review]
Also please update documentation as appropriate.

**Comment by Jackack** [comment]
I requested a change to add raw coordinates as well, if that's what you want. There's also already a dictionary of key points in engine.py. It's commented out by this commit but we should keep that feature too.

**Review by Jackack — CHANGES_REQUESTED** [review]
In engine.py, can you keep the starting_poses dictionary, and add the ability to use either distance or a key into the starting_poses dict?

**Comment by PatXue** [comment]
Added back in ability to use start_pos argument as a dictionary key for starting_poses

**Review by Jackack — APPROVED** [review]

**Review by Jackack — APPROVED** [review]

**Review by christianvluu — APPROVED** [review]

**Pull request merged**
