### PR TITLE
Sw/update velocity

### PR DESCRIPTION
**Pull request by PatXue**
Code for automatically changing velocity over time based on checkpoints on track

### CODE REVIEW

**Review by christianvluu — CHANGES_REQUESTED** [review]
Looks good but can you also add function/class headers like the other files?

**Review by Jackack — APPROVED** [review]

**Comment by Jackack** [comment]
Everything looks good but you need to pull the changes in main and merge them. Keep in mind that the topic names are remapped after the 2-buggy sim was merged into main. You will need to take the name of the buggy as a command line argument in your python file and prepend it to your topic paths. Consult the new 2d sim launch files for how to pass command line args via Roslaunch.

**Review by Jackack — DISMISSED** [review]
Everything looks good but you need to pull the changes in main and merge them. Keep in mind that the topic names are remapped after the 2-buggy sim was merged into main. You will need to take the name of the buggy as a command line argument in your python file and prepend it to your topic paths. Consult the new 2d sim launch files for how to pass command line args via Roslaunch.

**Review by christianvluu — APPROVED** [review]
Looks good to me, just Jack's change request left.

**Review by Jackack — APPROVED** [review]

**Pull request merged**
